import Head from "next/head";
import Image from "next/image";
import Navbar from "@components/globals/Navbar";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import PageLayout from "@components/globals/PageLayout";
import CustomCard from "@components/general/CustomCard";
import CustomPageIntro from "@components/general/CustomPageIntro";
// const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>Smithswork Consulting | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <CustomPageIntro
          image="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
          title="About Us"
          descriptions={[
            "Smithswork Consulting (Smithswork LLC) is a registered Management Consulting firm in the great state of Pennsylvania, USA.",
          ]}
          listTitle="We specialize in:"
          lists={[
            "Providing support for Business Development services to small businesses across the United States.",
            "We provide custom risk strategies through the provision of Insurance for both personal and commercial purposes.",
          ]}
        />
        <div className="p-2">

        <CustomCard
          // image="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
          title="Our Vision"
          description="We envision being the hallmark of support for small businesses in the great state of Pennsylvania and across the United State."
          shadowStyle={true}
        />
        <CustomCard
          // image="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
          title="Our Mission"
          description="We shall support small businesses through our affordable project support practice, our US-Africa trade activities, and our events with the goal of unleashing the potentials of small businesses."
          shadowStyle={true}
        />
        <div className="p-4 shadow-md rounded">
          <h2 className="text-2xl font-bold mb-2">Our Core Values</h2>
          <ul>
            <li className="ml-2 mb-2">Integrity</li>
            <li className="ml-2 mb-2">Excellence</li>
            <li className="ml-2 mb-2">Leadership</li>
            <li className="ml-2 mb-2">Professionalism</li>
          </ul>
        </div>
        </div>
      </PageLayout>
    </>
  );
}
