import Head from "next/head";
import Image from "next/image";
import Navbar from "@components/globals/Navbar";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import PageLayout from "@components/globals/PageLayout";
import CustomCard from "@components/general/CustomCard";
import CustomPageIntro from "@components/general/CustomPageIntro";
// const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>Smithswork Consulting | Our Approach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <CustomPageIntro
          image="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
          title="Our Approach"
          descriptions={[
            "Smithswork Consulting (Smithswork LLC) is a registered Management Consulting firm in the great state of Pennsylvania, USA.",
          ]}
        />
        <div className="p-2">
          <CustomCard
            image="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
            title="Innovation"
            description="Every project is our opportunity to birth out-of-the-box ideas and solutions to the most pressing need of our clients."
            shadowStyle={true}
          />
          <CustomCard
            image="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
            title="Cost"
            description="We pride ourselves in implementing projects with an eye on cost while meeting our client’s expectation."
            shadowStyle={true}
          />
          <CustomCard
            image="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
            title="Sustainability"
            description="We pay attention to how the implementation of our projects and client’s assignments birth negative externalities. The long-term consequence of our action today is one we do not take for granted."
            shadowStyle={true}
          />
        </div>
      </PageLayout>
    </>
  );
}
